import json
from datetime import datetime

from db_client.relational.base import Condition, ColumnConfig, ConditionCollection
from db_client.relational.oracle import DBAccessor, SQLCommand


# No test_select_gin_*/get_table_size here (unlike test_postgres.py): oracle.py intentionally
# doesn't implement select_gin/TagConfig or get_table_size - see the bottom of oracle.py for why.


class TestDBAccessor:
    TABLE = "test_db_accessor_tbl"

    def __init__(self):
        self.dba = DBAccessor(host="172.17.0.1")

    def test_run(self):
        result = self.dba.run("SELECT 1 FROM dual")
        assert result == [(1,)]

    def setup(self):
        self.dba.run(SQLCommand.drop_table(self.TABLE))
        col_cfgs = [
            ColumnConfig(column="id", sql_type="NUMBER", additional="GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ColumnConfig(column="name", sql_type="VARCHAR2(100)"),
            ColumnConfig(column="meta", sql_type="VARCHAR2(4000)"),
            ColumnConfig(column="created_at", sql_type="TIMESTAMP"),
        ]
        self.dba.run(SQLCommand.build_table(self.TABLE, col_cfgs))

    def teardown(self):
        self.dba.run(SQLCommand.drop_table(self.TABLE))
        self.dba.close()

    def test_insert_select_update_delete_roundtrip(self):
        # no RETURNING support on Oracle (see oracle.py's insert()) - look rows up by the
        # unique name instead of a returned id
        sql, params = SQLCommand.insert(self.TABLE, {"name": "alice", "meta": {"role": "admin"}})
        self.dba.run(sql, params)

        conditions = ConditionCollection(and_list=[Condition(key="name", match_type="exact", content="alice")], or_list=[])
        sql, params = SQLCommand.select(self.TABLE, conditions=conditions)
        row = self.dba.run(sql, params)[0]
        assert row[1] == "alice"
        # Oracle has no jsonb auto-deserialization like psycopg2 - meta comes back as plain text
        assert json.loads(row[2]) == {"role": "admin"}

        sql, params = SQLCommand.update(self.TABLE, {"name": "bob"}, conditions=conditions)
        self.dba.run(sql, params)
        bob_conditions = ConditionCollection(and_list=[Condition(key="name", match_type="exact", content="bob")], or_list=[])
        sql, params = SQLCommand.select(self.TABLE, cols=["name"], conditions=bob_conditions)
        assert self.dba.run(sql, params)[0][0] == "bob"

        sql, params = SQLCommand.delete(self.TABLE, bob_conditions)
        self.dba.run(sql, params)
        sql, params = SQLCommand.select(self.TABLE, conditions=bob_conditions)
        assert self.dba.run(sql, params) == []

    def test_insert_raw_sql_literal_and_empty_json_list(self):
        sql, params = SQLCommand.insert(
            self.TABLE, {"name": "empty_meta", "meta": [], "created_at": "SYSDATE"},
        )
        self.dba.run(sql, params)

        conditions = ConditionCollection(and_list=[Condition(key="name", match_type="exact", content="empty_meta")], or_list=[])
        sql, params = SQLCommand.select(self.TABLE, cols=["meta", "created_at"], conditions=conditions)
        meta, created_at = self.dba.run(sql, params)[0]
        assert json.loads(meta) == []
        # SYSDATE must be executed server-side as a function call, not stored as the literal string "SYSDATE"
        assert isinstance(created_at, datetime)

    def test_add_column_and_drop_column(self):
        self.dba.run(SQLCommand.add_column(self.TABLE, ColumnConfig(column="score", sql_type="NUMBER", additional="DEFAULT 0")))
        sql, params = SQLCommand.insert(self.TABLE, {"name": "scored"})
        self.dba.run(sql, params)
        conditions = ConditionCollection(and_list=[Condition(key="name", match_type="exact", content="scored")], or_list=[])
        sql, params = SQLCommand.select(self.TABLE, cols=["score"], conditions=conditions)
        assert self.dba.run(sql, params)[0][0] == 0

        self.dba.run(SQLCommand.drop_column(self.TABLE, "score"))
        sql, params = SQLCommand.select(self.TABLE, conditions=conditions)
        # the dropped column is gone, but the row itself is untouched
        assert len(self.dba.run(sql, params)) == 1


if __name__ == "__main__":
    obj = TestDBAccessor()
    obj.test_run()
    obj.setup()
    try:
        obj.test_insert_select_update_delete_roundtrip()
        obj.test_insert_raw_sql_literal_and_empty_json_list()
        obj.test_add_column_and_drop_column()
    finally:
        obj.teardown()

    print("all tests passed")
