# cd docker_change && docker build -t emc-adi-poc:local_v2 .

FROM emc-adi-poc:local

COPY figure_extractor.py /app/src/extractors/figure_extractor.py
COPY storage_manager.py /app/src/storage_manager.py
