services:
  vllm:
    image: 192.168.161.132:5000/vllm/vllm-openai:latest
    container_name: vllm
    ports:
      - "8106:8106"
    volumes:
      - ../../../_huggingface:/root/.cache/huggingface
      - ./:/app
    working_dir: /app
    entrypoint:  ["bash", "serve_emb_llm.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']  # Matches indices from host's nvidia-smi
              capabilities: [gpu]
