services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: 192.168.161.132:5000/llm_client:v1
    container_name: llm_client
    working_dir: /app
    environment:
      BASE_CFG_PATH: /app/cfgs/cfg.yaml
    volumes:
      - ./:/app
    command: "bash /app/env.sh"
