from db_client.relational.base import ColumnConfig, ConditionCollection, Condition
from db_client.relational.oracle import DBAccessor, SQLCommand


class TestSQLCommand:
    def __init__(self):
        self.dbaccessor = DBAccessor()
        self.dbaccessor.run(SQLCommand.drop_table("test_table"))

    def _test_build_table(self):
        cmd = SQLCommand.build_table(
            "test_table",
            [
                ColumnConfig("id", "NUMBER", "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
                ColumnConfig("name", "VARCHAR2(100)", ""),
                ColumnConfig("age", "NUMBER", "")
            ]
        )
        self.dbaccessor.run(cmd)
        assert self.dbaccessor.run("SELECT * FROM test_table") == []

    def _test_insert(self):
        cmd, params = SQLCommand.insert(
            "test_table",
            {
                "name": "歐巴馬",
                "age": 40
            }
        )
        self.dbaccessor.run(cmd, params)
        _, name, age = self.dbaccessor.run("SELECT * FROM test_table")[0]
        assert name == '歐巴馬' and age == 40

    def _test_update(self):
        cmd, params = SQLCommand.update(
            "test_table",
            {
                "name": "川普",
            },
            "WHERE name = '歐巴馬'"
        )
        self.dbaccessor.run(cmd, params)
        _, name, age = self.dbaccessor.run("SELECT * FROM test_table")[0]
        assert name == '川普' and age == 40

    def _test_select(self):
        cond_collect = ConditionCollection(
            and_list = [
                Condition(key="name", match_type="exact", content="川普"),
                Condition(key="age", match_type="range", lb=30, ub=50)
            ],
            or_list = [],
            concat_op = "AND"
        )
        cmd, params = SQLCommand.select("test_table", conditions=cond_collect)
        _, name, age = self.dbaccessor.run(cmd, params)[0]
        assert name == '川普' and age == 40

    def _test_delete(self):
        cond_collect = ConditionCollection(
            and_list = [
                Condition(key="name", match_type="exact", content="川普")
            ],
            or_list = [],
            concat_op = "AND"
        )
        cmd, params = SQLCommand.delete("test_table", conditions=cond_collect)
        self.dbaccessor.run(cmd, params)
        self.dbaccessor.run(cmd, params)
        assert self.dbaccessor.run("SELECT * FROM test_table") == []

    def test_run_all(self):
        self._test_build_table()
        self._test_insert()
        self._test_update()
        self._test_select()
        self._test_delete()
        self.dbaccessor.run(SQLCommand.drop_table("test_table"))


if __name__ == "__main__":
    TestSQLCommand().test_run_all()
